name: Test and deploy

on:
  push:
    branches: [master, main]

jobs:
  test:
    name: Run Lint and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # v3→v4

      - uses: actions/setup-node@v4 # v3→v4

      - uses: pnpm/action-setup@v2

      - run: pnpm install --frozen-lockfile

      - run: pnpm test # 或 echo 'skip'

  build:
    name: Build docs
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4 # v3→v4

      - uses: actions/setup-node@v4 # v3→v4

      - uses: pnpm/action-setup@v2

      - run: pnpm install --frozen-lockfile

      - run: pnpm --filter @kiyo-element/docs build

      - name: Upload docs
        uses: actions/upload-artifact@v4 # ✅ v3→v4
        with:
          name: docs
          path: ./packages/docs/.vitepress/dist

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download docs
        uses: actions/download-artifact@v4 # ✅ v3→v4
        with:
          name: docs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4 # 顺便升级
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
